# Build task-tracker.
FROM node:18-alpine AS build

WORKDIR /usr/src/app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

# Run task-tracker
FROM nginx:1.23-alpine

WORKDIR /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/task-tracker .
